# Generated by Django 4.0.3 on 2023-06-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('enrollment', models.CharField(max_length=20, unique=True)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.school', verbose_name='Category')),
            ],
        ),
    ]
